dist: trusty
sudo: required
language: node_js

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install --silent

notifications:
  email:
    on_success: never
    on_failure: never

script:
- npm run test
- npm run tslint
- npm run tscheck
- npm run freezer
- npm run freezer:validate
